site_name: Order Management System Docs
theme:
  name: material

nav:
  - Головна: README.md
  - Архітектура (Architecture):
    - System Specification (SSD): architecture/SSD.md
    - Software Design (SDD): architecture/SDD.md
    - Infrastructure (ISD): architecture/ISD.md
  - API (Контракти):
    - OpenAPI (Swagger): openapi.yaml  # Твій створений файл OpenAPI
  - Забезпечення якості (Quality):
    - Test Strategy: quality/test-strategy.md
    - UI Storybook: frontend/storybook-components.md
  - Автоматизація (DevOps):
    - CI/CD та DoD: ci-cd-and-dod.md